### ISSUE TITLE
Three Geometry is deprecated and removed port to BufferGeometry

### ISSUE THREAD

**Issue by arpu** [juniorxsound/Depthkit.js#21]
Hey,

any plans to support THREEjs BufferGeometry?

**Comment by ROBYER1** [comment]
Wondering this too

**Comment by ROBYER1** [comment]
Try this branch https://github.com/juniorxsound/Depthkit.js/tree/dependabot/npm_and_yarn/three-0.137.0

**Comment by ROBYER1** [comment]
> Hi 👋 thanks for opening this issue.
> 
> Totally agree we should migrate over to BufferGeometry - I currently have no bandwidth to do that but if anyone wants to open a PR i'd be happy to review and provide some feedback

Just cracked it here, hopefully can be merged, just need to build depthkit.min,js because I wasn't sure how to do that but I rebuilt depthkit.js in build folder https://github.com/juniorxsound/Depthkit.js/pull/30

**Comment by juniorxsound** [comment]
@ROBYER1 @arpu this has now been merged 🙏

**Comment by ROBYER1** [comment]
Thanks! I was going to look into fully updating to the very latest Three.js but hit some other issues there, this works good for what I needed though!

**Comment by ROBYER1** [comment]
I forgot to add, I got DepthKit.js running in Needle which has support for desktop/AR/MR/VR 
Needle Example:
https://outgoing-exuberant-cheshire.glitch.me/

More about Needle:
https://needle.tools/
