### ISSUE TITLE
Metadata parsing problem

### ISSUE THREAD

**Issue by sergiobd** [juniorxsound/Depthkit.js#9]
The metadata that gets exported from depthkit app (without refinement workflow), does not match the format that this library expects, therefore clips cannot be loaded. Example:

`{
	"_versionMajor" : "0",
	"_versionMinor" : "1",
	"depthFocalLength" : {
		"x" : 505.453,
		"y" : 505.598
	},
	"depthImageSize" : {
		"x" : 640,
		"y" : 576
	},
	"depthPrincipalPoint" : {
		"x" : 321.734,
		"y" : 334.185
	},
	"farClip" : 8.192,
	"format" : "perpixel",
	"nearClip": 0.25,
	"clipEpsilon" : 0.000629564
}
`
Are the rest of the parameters not necessary? Why are they not exported in current depthkit version?

**Comment by juniorxsound** [comment]
Thanks @sergiobd! This repository uses the old Depthkit metadata structure and hasn't been updated yet to the new format. In the meantime you can use [Scatter's fork](https://github.com/ScatterCo/Depthkit.js) which implements the new metadata format. Hopefully given a bit more free time I'll get around to updating it here as well :pray:
